<?php
/**
 * @file
 * Farm weather module.
 */

/**
 * Implements hook_farm_log_categories().
 */
function farm_weather_farm_log_categories() {

  // Provide an "Weather" log category.
  return array('Weather');
}

/**
 * Implements hook_farm_client_modules().
 */
function farm_weather_farm_client_modules() {
  return array(
    array(
      'name' => 'weather',
      'label' => t('Weather'),
      'js' => drupal_get_path('module', 'farm_weather') . '/src/FieldModule/Weather/weather.js',
    ),
  );
}
